spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET_DEV}
