spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${BD_URL}
    username: ${BD_USERNAME}
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  port: 80

jwt:
  secret-key: ${JWT_SECRET_PRD}
  expiration-ms: 7200000
